### ISSUE TITLE
parser plugins should parse top-level unknown and void elements

### ISSUE THREAD

**Issue by bantic** [bustle/mobiledoc-kit#494]
The Section parser first infers a section type for a given element before attempting to parse its child nodes, and it only runs its parser plugins against the child nodes. This means that HTML with root-level elements do not get run through the plugins. This happens (in slightly different ways) with both void elements and elements with childNodes:
- `parse('<video>...</video>')` — plugins skip `<video>`
- `parse('<video>')` — plugins skip  `video`

**Comment by kevinansfield** [comment]
I've just run into this too. I'd like to be able to parse `<figure><img/><figcaption>Foo</figcaption></figure>` into our `image` card in order to extract the caption for the payload but the `<figure>` element never hits the parser plugins, only the `<img>`.

I have a similar problem where a `<hr />` element doesn't get passed to the parser plugins so we're unable to convert it to our `divider` card. Is this the same problem or does that stem from somewhere else?
