### ISSUE TITLE
Double-clicking a link in Firefox causes hasActiveMarkup('a') to report incorrect results

### ISSUE THREAD

**Issue by chrisdpeters** [bustle/mobiledoc-kit#543]
Maybe I'm not coding something correctly on my end. So here is the gist of what I'm doing:

```javascript
editor.cursorDidChange(() => {
  editor.run(() => {
    let hasActiveLink = editor.hasActiveMarkup('a');
    let hasSelectedRange = !editor.range.isCollapsed;
    this.set('enableLinkButton', hasActiveLink || hasSelectedRange);
  });
});
```

All is fine across browsers until I double-click a linked word in Firefox. The UI correctly highlights the entire word, but `hasActiveLink` is `false` only in that scenario.

The answer to this Stack Overflow question is probably the [closest thing that I could find to a possible explanation](http://stackoverflow.com/questions/19234988/firefox-how-to-get-selected-text-when-using-double-click) of what's going on. When I poke around in the Mobiledoc source, it seems to match what's described in the answer: the parent node ends up being the containing `p` element and not the `a`, so I think that means it's including the `a` in the selection.

**Comment by bantic** [comment]
@chrisdpeters Thanks for explaining, and sleuthing that SO question. Yes, that looks like the correct description of what is happening in mobiledoc-kit, and would explain the behavior you're seeing. Firefox's alternative handling of selection state makes this harder than it would otherwise be. (Although FF's alt selection handling also exempted it from #486, so I suppose it goes both ways).
Looks like we can update/improve the selection->Position code in mobiledoc's `Position` class — it should descend into the first child of the selected node if the browser's selection reports that the selected anchor and focus nodes are not text nodes. Might be some more heuristics to correctly catch this case, but should be doable. Thank you for reporting it.

**Comment by chrisdpeters** [comment]
@bantic No problem. I'm not sure that I have enough free time to help now, but would you mind pointing me to a place or two in the source that would be a good place to start poking around? I did take an hour to see what I could figure out, and I never felt quite sure that I was looking in the right place.
