### ISSUE TITLE
Security: Links allow arbitrary code injection

### ISSUE THREAD

**Issue by boydkr** [bustle/mobiledoc-kit#552]
A link set using arbitrary javascript will be happily executed in the browser, i.e.
`javascript:alert('Inject very bad code');`

This is a security concern for an application where users can add links that other users can access.

**Comment by bantic** [comment]
Thanks for reporting. The mobiledoc renderers [escape unsafe HREF attributes](https://github.com/bustle/mobiledoc-dom-renderer#attribute-sanitization-xss-protection), so it shouldn't be possible for malicious user A to author a bad mobiledoc that is then rendered for display to user B.
But you're right that user A authored a mobiledoc with unsafe href value, and the same mobiledoc is presented in editable form to user B, it wouldn't be escaped. This is a less common use case (typically we assume that a mobiledoc won't be edited by multiple untrusted users), but it's a good one to point out. It appears that, because the `<a>` tags are displayed inside contentEditable they are not clickable directly, but the tooltip popup does include the clickable linked text. This mitigates the issues somewhat but doesn't prevent it entirely.

**Comment by sdhull** [comment]
I'm no infosec expert but @bantic's explanation of how this is mitigated by mobiledoc seems sufficient to me. I'd close out this issue. ✌️

**Comment by hbrysiewicz** [comment]
It appears that mobiledoc disallows `javascript:alert('Inject very bad code');` but it seems that it still allows things like `jaVasCript::alert('Inject very bad code');`
