### ISSUE TITLE
Improve build tooling and package consumption

### ISSUE THREAD

**Issue by gpoitch** [bustle/mobiledoc-kit#570]
For example, to access the parser in node environment, you currently have to do this:

```js
const parser = require('mobiledoc-kit/dist/commonjs/mobiledoc-kit/parsers/mobiledoc').default
```

instead of:
```js
const parser = require('mobiledoc-kit/parsers/mobiledoc')
```

It's also not providing entry points for module bundlers that can take advantage of tree-shaking.
I can lend a hand by using rollup instead of broccoli.

**Comment by iezer** [comment]
@gpoitch Thanks for opening this issue. I've worked on modernizing the build by using rollup and I have a branch here. https://github.com/bustle/mobiledoc-kit/tree/iezer/rollup It allows to to remove the outdated dependencies on `broccoli-multi-builder` and `broccoli-test-builder`.

I'm not sure this solves your use-case because rollup by definition only exposes functionality that is exported in `src/js/index.js`. That does not currently include the parser. Do you think the parser should be part of the object exported from `index.js`? Or perhaps exported as a separate AMD module?

I'd appreciate it if you could take a look at my branch, try out the build locally and let me know if it solves your use case. I'd also appreciate your feedback on if there's anyway rollup should be configured differently.

So far I'm noticing a very slight decrease in payload size with Rollup (The un-minified AMD build went down 7KB from 544 KB to 537 KB) but build times are slightly higher.

CC @rondale-sc
