### ISSUE TITLE
addSection in parserPlugins obliterate previous section content in certain cases

### ISSUE THREAD

**Issue by sdhull** [bustle/mobiledoc-kit#683]
For a demo see https://jsfiddle.net/1rmndk8w/4/

The way I discovered this was by copying & pasting a github comment with an image. I found that the text immediately preceding the image was gone after pasting.

I believe this is because `state.text` is not properly tracking everything but I'm not exactly intimately familiar with the code so I'm not certain.
```js
      addSection: (section) => {
        // avoid creating empty paragraphs due to wrapper elements around
        // parser-plugin-handled elements
        if (this.state.section.isMarkerable && !this.state.text) {
          this.state.section = null;
        } else {
          this._closeCurrentSection();
        }
        this.sections.push(section);
      },
```
One thing that is interesting is that in this case, `this.state.section.text` has the text but `this.state.text` is an empty string. Perhaps this check could be changed to include `this.state.section.text`?

/cc @kevinansfield

**Comment by kevinansfield** [comment]
@sdhull you were spot on with the required change to the conditional, PR opened with the change and a test here https://github.com/bustle/mobiledoc-kit/pull/685

The reason `this.state.text` was blank yet `this.state.section.text` wasn't is because the `<a>` element parsing [calls `createMarker()`](https://github.com/bustle/mobiledoc-kit/blob/master/src/js/parsers/section.js#L242-L245) which migrates the temporary `this.state.text` into a marker in the section.

**Comment by sdhull** [comment]
Thank you @kevinansfield! 🙏
