### ISSUE TITLE
Non-breaking spaces are ignored by the editor

### ISSUE THREAD

**Issue by xDEADC0DE** [bustle/mobiledoc-kit#700]
I cannot add non-breaking spaces to the editor, using Chrome on Windows and Ghost. (https://github.com/TryGhost/Ghost )

Whether I type it with Ctrl+Shift+Space, or paste it from somewhere else nothing gets added to the text (pasting " :" only adds the ":").

Please note that this is not simply a formatting issue ; I'm writing a blog post in French where non-breaking spaces are part of the usual typography.

**Comment by xDEADC0DE** [comment]
Is this project still active?

**Comment by gpoitch** [comment]
This seems to be working correctly. Perhaps it got fixed along the way, as this issue is old.

On Mac, if I enter option+space to insert a non-breaking space it appears correctly. When I copy the content and paste it in my text editor, it shows the non-breaking space differentiation from a regular space.

If not fixed for you, maybe a windows issue?
